# FeatherStore Configuration File

# Storage configuration
storage:
  # DuckDB storage settings (short-term, high-performance storage)
  duckdb:
    # Path to the DuckDB database file
    path: "./data/features.db"
    # Memory limit for DuckDB
    memory_limit: "4GB"
    # Maximum number of concurrent connections
    max_connections: 10

  # Parquet storage settings (long-term archival storage)
  parquet:
    # Directory to store Parquet files
    directory: "./data/features"
    # Row group size for Parquet files (rows per group)
    row_group_size: 131072
    # Compression algorithm (snappy, gzip, etc.)
    compression: "snappy"

  # Time after which features are moved from DuckDB to Parquet storage
  archive_after: "24h"

# Server configuration
server:
  # HTTP API port
  http_port: 8080
  # Arrow Flight RPC port
  flight_port: 8081
  # HTTP read timeout
  read_timeout: "30s"
  # HTTP write timeout
  write_timeout: "30s"
  # Maximum request size
  max_request_size: 52428800 # 50MB

# Metrics configuration
metrics:
  # Prometheus metrics port
  prometheus_port: 9090
  # Enable metrics collection
  enabled: true

# Logging configuration
logging:
  # Log level (debug, info, warn, error)
  level: "info"
  # Log format (json or text)
  format: "json"
  # Output path (stdout, stderr, or file path)
  output_path: "stdout"
